M gptypes
NSS-Wacky-Eels/BangazonAPI pull request #19
Opened 2018-10-29 18:52 UTC by ThraxHamilton

2018-10-29 20:36 UTC, MissPeperr requested changes
POST is throwing "SqlException: Cannot insert explicit value for identity column in table 'ProductType' when IDENTITY_INSERT is set to OFF".
PUT does not work.

2018-10-30 18:46 UTC, ThraxHamilton commented
## Link to Ticket
https://github.com/NSS-Wacky-Eels/BangazonAPI/issues/3
## Description of Proposed Changes

- Fixed POST to update ID instead of Name.

## Steps to Test

POST
```sh
git fetch --all
git checkout <MGptypes>

```


## Impacted Areas in Application

List general components of the application that this PR will affect:

* Product Types

2018-10-30 20:04 UTC, MissPeperr approved these changes

2018-10-30 20:11 UTC, streatorward approved these changes
Lookin good to me fam

2018-10-30 20:53 UTC, merged